- hosts: localhost
  user: root
  connection: local
  gather_facts: no
  tasks:
  - debug:
      msg: "Sleeping First Time"
  - name: First Wait
    wait_for:
      timeout: 60
  - debug:
      msg: "Sleeping Second time"
  - name: Second Wait
    wait_for:
      timeout: 120
  - debug:
      msg: "Sleeping Third time"
  - name: Third Wait
    wait_for:
      timeout: 60
  - debug:
      msg: "Done Sleeping"
