---
# This playbook prints a simple debug message
- name: Echo Hello, world!
  hosts: localhost
  
  tasks:
  - debug: msg="Hello, world!"
  - set_fact:
      my_date: ansible_date_time.date
      my_time: ansible_date_time.time
